#! /bin/bash


if [ "$1" != "" ]; then
        export MJ="-j$1"
else
        export MJ=""
fi
export PACKAGE=$(basename -- "$PWD")
read -p "Number of make jobs: $MJ" &&

echo "[ $PACKAGE ] Configuring ..." && 
./configure \
  CROSS_COMPILE=${MLFS_TARGET}- \
  --prefix=/ \
  --target=${MLFS_TARGET} &&
  
read -p "[ $PACKAGE Static] Compile?" &&
time { make $MJ ; } &&

read -p "Install?" &&
DESTDIR=/cross-tools make install
mkdir -v /cross-tools/usr
ln -sv ../include  /cross-tools/usr/include
