#! /bin/bash
# step 15 originally
if [ "$1" != "" ]; then
        export MJ="-j$1"
else
        export MJ=""
fi
export PACKAGE=$(basename -- "$PWD")
read -p "Number of make jobs: $MJ" &&

export CC="${MLFS_TARGET}-gcc"
export CXX="${MLFS_TARGET}-g++"
export AR="${MLFS_TARGET}-ar"
export AS="${MLFS_TARGET}-as"
export RANLIB="${MLFS_TARGET}-ranlib"
export LD="${MLFS_TARGET}-ld"
export STRIP="${MLFS_TARGET}-strip"

echo "[ TC - $PACKAGE ] Patch source ..." &&
cp Makefile{,.orig}
sed -e "/^all:/s/ test//" Makefile.orig > Makefile
sed -i 's@\(ln -s -f \)$(PREFIX)/bin/@\1@' Makefile
sed -i "s@(PREFIX)/man@(PREFIX)/share/man@g" Makefile


echo "[ TC - $PACKAGE ] Configure source ..." &&
make -f Makefile-libbz2_so CC="${CC}" AR="${AR}" RANLIB="${RANLIB}" $MJ
make clean $MJ

read -p "[ TC - $PACKAGE ] Compile?" &&
time { make CC="${CC}" AR="${AR}" RANLIB="${RANLIB}" $MJ ; } &&

read -p "[ TC - $PACKAGE ] Install?" &&
make PREFIX=/tools install
