#! /bin/bash


if [ "$1" != "" ]; then
        export MJ="-j$1"
else
        export MJ=""
fi
export PACKAGE=$(basename -- "$PWD")
read -p "Number of make jobs: $MJ" &&

echo "[ $PACKAGE ] Adding auxillary sources ..." && 
tar -xf ../mpfr-4.0.2.tar.xz
mv -v mpfr-4.0.2 mpfr
tar -xf ../gmp-6.1.2.tar.xz
mv -v gmp-6.1.2 gmp
tar -xf ../mpc-1.1.0.tar.gz
mv -v mpc-1.1.0 mpc

mkdir -v build && cd  build
echo "[ $PACKAGE ] Configuring ..." && 
CFLAGS='-g0 -O0' \
CXXFLAGS='-g0 -O0' \
../configure \
          --prefix=/cross-tools --build=${MLFS_HOST} \
          --host=${MLFS_HOST}   --target=${MLFS_TARGET} \
          --with-sysroot=/cross-tools/${MLFS_TARGET} \
          --disable-nls         --with-newlib  \
          --disable-libitm     --disable-libvtv \
          --disable-libssp     --disable-shared \
          --disable-libgomp    --without-headers \
          --disable-threads    --disable-multilib \
          --disable-libatomic  --disable-libstdcxx \
          --enable-languages=c --disable-libquadmath \
          --disable-libsanitizer --with-arch=${MLFS_CPU} \
          --disable-decimal-float --enable-clocale=generic
read -p "[ $PACKAGE Static] Compile?" &&
time { make all-gcc all-target-libgcc $MJ ; } &&
read -p "[ $PACKAGE Static] Install?"
make install-gcc install-target-libgcc
