#! /bin/bash


if [ "$1" != "" ]; then
        export MJ="-j$1"
else
        export MJ=""
fi
export PACKAGE=$(basename -- "$PWD")
read -p "Number of make jobs: $MJ" &&

echo "[ $PACKAGE ] Configuring ..." && 
./configure --prefix=/cross-tools --disable-libseccomp
read -p "[ $PACKAGE ] Compile?" &&
time { make $MJ ; } &&
read -p "[ $PACKAGE ] Install?"
make install
