#! /bin/bash


if [ "$1" != "" ]; then
        export MJ="-j$1"
else
        export MJ=""
fi
export PACKAGE=$(basename -- "$PWD")
read -p "Number of make jobs: $MJ" &&

echo "[ TC - $PACKAGE ] Configuring ..." && 
./configure \
  CROSS_COMPILE=${MLFS_TARGET}- \
  --prefix=/ \
  --target=${MLFS_TARGET} &&

read -p "[ TC - $PACKAGE ] Compile?" &&
time { make $MJ ; } &&

read -p "[ TC - $PACKAGE ] Install?"
make DESTDIR=/tools install

case $(uname -m) in
  x86_64)  rm -v  /tools/lib/ld-musl-x86_64.so.1
           ln -sv libc.so /tools/lib/ld-musl-x86_64.so.1
           ;;
  i686)    rm -v  /tools/lib/ld-musl-i686.so.1
           ln -sv libc.so /tools/lib/ld-musl-i686.so.1
           ;;
  arm*)    rm -v  /tools/lib/ld-musl-arm.so.1
           ln -sv libc.so /tools/lib/ld-musl-arm.so.1
           ;;
esac
