#! /bin/bash
# step 14 originally
if [ "$1" != "" ]; then
        export MJ="-j$1"
else
        export MJ=""
fi
export PACKAGE=$(basename -- "$PWD")
read -p "Number of make jobs: $MJ" &&

export CC="${MLFS_TARGET}-gcc"
export CXX="${MLFS_TARGET}-g++"
export AR="${MLFS_TARGET}-ar"
export AS="${MLFS_TARGET}-as"
export RANLIB="${MLFS_TARGET}-ranlib"
export LD="${MLFS_TARGET}-ld"
export STRIP="${MLFS_TARGET}-strip"

case $(uname -m) in
  x86_64)  ln -sv lib /tools/lib64 ;;
esac


echo "[ TC - $PACKAGE ] Configuring ..." && 
mkdir -v build && cd build
../configure                   \
    --target=${MLFS_TARGET}    \
    --build=${MLFS_HOST}       \
    --host=${MLFS_TARGET}      \
    --prefix=/tools            \
    --disable-nls              \
    --disable-werror           \
    --with-lib-path=/tools/lib \
    --with-sysroot

read -p "[ TC - $PACKAGE ] Compile?" &&
time { make $MJ ; } &&

read -p "[ TC - $PACKAGE ] Install?" &&
make install &&
make -C ld clean $MJ &&
make -C ld LIB_PATH=/usr/lib:/lib $MJ &&
cp -v ld/ld-new /tools/bin 
