#! /bin/bash
# step 15 originally
if [ "$1" != "" ]; then
        export MJ="-j$1"
else
        export MJ=""
fi
export PACKAGE=$(basename -- "$PWD")
read -p "Number of make jobs: $MJ" &&

export CC="${MLFS_TARGET}-gcc"
export CXX="${MLFS_TARGET}-g++"
export AR="${MLFS_TARGET}-ar"
export AS="${MLFS_TARGET}-as"
export RANLIB="${MLFS_TARGET}-ranlib"
export LD="${MLFS_TARGET}-ld"
export STRIP="${MLFS_TARGET}-strip"

echo "[ TC - $PACKAGE LIBSTDCXX ] Patching  source ..." &&
patch -Np0 -i ../patches/gcc-9.1.0-void-patches/0010-ldbl128-config.patch
patch -Np0 -i ../patches/gcc-9.1.0-void-patches/ada-shared.patch
patch -Np0 -i ../patches/gcc-9.1.0-void-patches/fix-cxxflags-passing.patch
patch -Np0 -i ../patches/gcc-9.1.0-void-patches/fix-musl-execinfo.patch
patch -Np0 -i ../patches/gcc-9.1.0-void-patches/libgcc-musl-ldbl128-config.patch
patch -Np0 -i ../patches/gcc-9.1.0-void-patches/musl-ada.patch
patch -Np0 -i ../patches/gcc-9.1.0-void-patches/no-stack_chk_fail_local.patch
patch -Np0 -i ../patches/gcc-9.1.0-void-patches/non-nullness.patch

echo "[ TC - $PACKAGE LIBSTDCXX ] Configure source ..." &&
mkdir -v build && cd build
../libstdc++-v3/configure           \
    --target=${MLFS_TARGET}         \
    --build=${MLFS_HOST}            \
    --host=${MLFS_TARGET}           \
    --prefix=/tools                 \
    --disable-multilib              \
    --disable-nls                   \
    --disable-libstdcxx-threads     \
    --disable-libstdcxx-pch         \
    --with-gxx-include-dir=/tools/${MLFS_TARGET}/include/c++/9.2.0 &&
    
read -p "[ TC - $PACKAGE LIBSTDCXX ] Compile?" &&
time { make $MJ ; } &&

read -p "[ TC - $PACKAGE LIBSTDCXX ] Install?" &&
make install
