#! /bin/bash
# step 15 originally
if [ "$1" != "" ]; then
        export MJ="-j$1"
else
        export MJ=""
fi
export PACKAGE=$(basename -- "$PWD")
read -p "Number of make jobs: $MJ" &&

export CC="${MLFS_TARGET}-gcc"
export CXX="${MLFS_TARGET}-g++"
export AR="${MLFS_TARGET}-ar"
export AS="${MLFS_TARGET}-as"
export RANLIB="${MLFS_TARGET}-ranlib"
export LD="${MLFS_TARGET}-ld"
export STRIP="${MLFS_TARGET}-strip"

echo "[ TC - $PACKAGE ] Patching  source ..." &&
patch -Np1 -i ../patches/expect-5.45.3-dont-put-toolchain-in-libpath.patch
patch -Np1 -i ../patches/expect-5.45.3-dont-configure-testsuites.patch
patch -Np1 -i ../patches/expect-5.45.3-allow-cross-compile.patch
cp -v ../files/config.guess-musl tclconfig/config.guess
cp -v ../files/config.sub-musl tclconfig/config.sub
cp -v configure{,.orig}
sed 's:/usr/local/bin:/bin:' configure.orig > configure

echo "[ TC - $PACKAGE ] Configure source ..." &&
./configure --build=${MLFS_HOST} \
            --host=${MLFS_TARGET} \
            --prefix=/tools \
            --with-tcl=/tools/lib \
            --with-tclinclude=/tools/include &&

read -p "[ TC - $PACKAGE ] Compile?" &&
time { make $MJ ; } &&

read -p "[ TC - $PACKAGE ] Install?" &&
make SCRIPTS="" install

