#! /bin/bash
# step 15 originally
if [ "$1" != "" ]; then
        export MJ="-j$1"
else
        export MJ=""
fi
export PACKAGE=$(basename -- "$PWD")
read -p "Number of make jobs: $MJ" &&

export CC="${MLFS_TARGET}-gcc"
export CXX="${MLFS_TARGET}-g++"
export AR="${MLFS_TARGET}-ar"
export AS="${MLFS_TARGET}-as"
export RANLIB="${MLFS_TARGET}-ranlib"
export LD="${MLFS_TARGET}-ld"
export STRIP="${MLFS_TARGET}-strip"

echo "[ TC - $PACKAGE ] Patch source ..." &&
patch -Np1 -i ../patches/coreutils-8.31-fix-strtod.patch

echo "[ TC - $PACKAGE ] Re-create configure script ..." &&
autoreconf -vif &&
sed -i '/test.lock/s/^/#/' gnulib-tests/gnulib.mk

echo "[ TC - $PACKAGE ] Configure source ..." &&
fu_cv_sys_stat_statfs2_bsize=no \
ac_cv_func_syncfs=no \
gl_cv_func_working_mkstemp=yes \
gl_cv_func_working_acl_get_file=yes \

./configure --build=${MLFS_HOST} \
            --host=${MLFS_TARGET} \
            --prefix=/tools \
            --enable-install-program=hostname &&

read -p "[ TC - $PACKAGE ] Compile?" &&
time { make $MJ ; } &&

read -p "[ TC - $PACKAGE ] Install?" &&
make install
