#! /bin/bash
# step 15 originally
if [ "$1" != "" ]; then
        export MJ="-j$1"
else
        export MJ=""
fi
export PACKAGE=$(basename -- "$PWD")
read -p "Number of make jobs: $MJ" &&

export CC="${MLFS_TARGET}-gcc"
export CXX="${MLFS_TARGET}-g++"
export AR="${MLFS_TARGET}-ar"
export AS="${MLFS_TARGET}-as"
export RANLIB="${MLFS_TARGET}-ranlib"
export LD="${MLFS_TARGET}-ld"
export STRIP="${MLFS_TARGET}-strip"

echo "[ TC - $PACKAGE ] Merge perl-cross source " &&
cd .. &&
tar xf perl-cross-1.3.tar.gz
cd perl-5.30.0 &&
mv -v ../perl-cross-1.3/* ./
mv -v ../perl-cross-1.3/utils/* utils/

echo "[ TC - $PACKAGE ] Patch source " &&
patch -p1 < ../patches/perl-5.30-alpine/musl-locale.patch

echo "[ TC - $PACKAGE ] Configure source ..." &&
./configure --prefix=/tools \
            --target=${MLFS_TARGET} &&

read -p "[ TC - $PACKAGE ] Compile?" &&
time { make $MJ ; } &&

read -p "[ TC - $PACKAGE ] Install?" &&
cp -v perl cpan/podlators/scripts/pod2man /tools/bin &&
mkdir -pv /tools/lib/perl5/5.30.0 &&
cp -Rv lib/* /tools/lib/perl5/5.30.0 

