#! /bin/bash
# Cross-Tools: GCC STATIC
# Build and install as mlfs
# Source: http://ftp.gnu.org/gnu/gcc/gcc-9.1.0/gcc-9.1.0.tar.xz

tar -xf ../mpfr-4.0.2.tar.xz
mv -v mpfr-4.0.2 mpfr
tar -xf ../gmp-6.1.2.tar.xz
mv -v gmp-6.1.2 gmp
tar -xf ../mpc-1.1.0.tar.gz
mv -v mpc-1.1.0 mpc
mkdir -v build && cd  build &&
CFLAGS='-g0 -O0' \
CXXFLAGS='-g0 -O0' \
../configure \
	  --prefix=/cross-tools --build=${MLFS_HOST} \
	  --host=${MLFS_HOST}   --target=${MLFS_TARGET} \
	  --with-sysroot=/cross-tools/${MLFS_TARGET} \
	  --disable-nls  --with-newlib \
	  --disable-libitm     --disable-libvtv \
	  --disable-libssp     --disable-shared \
	  --disable-libgomp    --without-headers \
	  --disable-threads    --disable-multilib \
	  --disable-libatomic  --disable-libstdcxx \
	  --enable-languages=c --disable-libquadmath \
	  --disable-libsanitizer --with-arch=${MLFS_CPU} \
	  --disable-decimal-float --enable-clocale=generic &&
make all-gcc all-target-libgcc -j2 &&
make install-gcc install-target-libgcc
