#! /bin/bash
# Cross-Tools: Musl
# Build and install as mlfs
# source: https://www.musl-libc.org/releases/musl-1.1.23.tar.gz

./configure \
  CROSS_COMPILE=${MLFS_TARGET}- \
  --prefix=/ \
  --target=${MLFS_TARGET} &&
make -j2 && DESTDIR=/cross-tools make install &&
mkdir -v /cross-tools/usr &&
ln -sv ../include  /cross-tools/usr/include
