#! /bin/bash
# Tool Chain: Binutils PASS 1 of 2
# Build and install as mlfs

export CC="${MLFS_TARGET}-gcc" &&
export CXX="${MLFS_TARGET}-g++" &&
export AR="${MLFS_TARGET}-ar" &&
export AS="${MLFS_TARGET}-as" &&
export RANLIB="${MLFS_TARGET}-ranlib" &&
export LD="${MLFS_TARGET}-ld" &&
export STRIP="${MLFS_TARGET}-strip" &&

mkdir -v build && cd build &&
../configure --prefix=/tools            \
             --with-sysroot=$MLFS        \
             --with-lib-path=/tools/lib \
             --build=${MLFS_HOST} \
             --host=${MLFS_TARGET} \
             --target=${MLFS_TARGET}          \
             --disable-nls              \
             --disable-werror &&

make -j4 &&

case $(uname -m) in
  x86_64)  ln -sv lib /tools/lib64 ;;
esac
read -p "Install?" &&
make install 
#read -p "Build 2nd linker?" &&
#make -C ld clean -j2 &&
#make -C ld LIB_PATH=/tools/lib -j2 &&
#cp -v ld/ld-new /tools/bin
