#! /bin/bash
# syntax *.build <package.tar.xz> <number of make jobs>

source $MLFS/sources/scripts/000-autobuild.config &&

export PACKAGE=$(echo "$1" | sed -n '/\.tar\.gz$/s///p' )
cd $PACKAGE &&
############################################################
echo "[ CT 4/6 - $PACKAGE ] Configure source..." |& tee -a  ~/build.log &&
./configure \
  CROSS_COMPILE=${MLFS_TARGET}- \
  --prefix=/ \
  --target=${MLFS_TARGET} &&

echo "[ CT 4/6 - $PACKAGE ] Compile.." |& tee -a  ~/build.log  &&
make $MJ  &&

echo "[ CT 4/6 - $PACKAGE ] Install ..." |& tee -a  ~/build.log &&
DESTDIR=/cross-tools make install &&
mkdir -pv /cross-tools/usr &&
ln -sv ../include  /cross-tools/usr/include &&
case $(uname -m) in
  x86_64) export ARCH="x86_64"
            ;;
  i686)   export ARCH="i386"
            ;;
  arm*)   export ARCH="arm"
            ;;
  aarch64) export ARCH="aarch64"
            ;;
esac &&

ln -sv ../lib/ld-musl-$ARCH.so.1 /cross-tools/bin/ldd &&
mkdir -v /cross-tools/etc &&
touch /cross-tools/etc/ld-musl-$ARCH.path &&
echo "/cross-tools/lib" >> /cross-tools/etc/ld-musl-$ARCH.path &&
echo "/tools/lib" >> /cross-tools/etc/ld-musl-$ARCH.path &&
unset ARCH &&
cd .. && rm -rf $PACKAGE

