#! /bin/bash
# syntax *.build <package.tar.xz> <number of make jobs>

source $MLFS/sources/scripts/000-autobuild.config &&

export PACKAGE=$(echo "$1" | sed -n '/\.tar\.xz$/s///p' )
cd $PACKAGE &&
############################################################
echo "[ CT 5/6 - $PACKAGE Final ] Adding auxillary sources ..." |& tee -a  ~/build.log &&
tar -xf ../mpfr-* &&
mv $( echo "$(ls ../mpfr-*)" | sed -n '/\.tar\.xz$/s///p' | cut -d "/" -f 2 ) mpfr &&
tar -xf ../gmp-* &&
mv $( echo "$(ls ../gmp-*)" | sed -n '/\.tar\.xz$/s///p' | cut -d "/" -f 2 ) gmp &&
tar -xf ../mpc-* &&
mv $( echo "$(ls ../mpc-*)" | sed -n '/\.tar\.gz$/s///p' | cut -d "/" -f 2 ) mpc &&

echo "[ CT 5/6 - $PACKAGE Final ] Patching  source..." |& tee -a  ~/build.log  &&
patch -Np0 -i ../patches/gcc-9.1.0-void-patches/0010-ldbl128-config.patch 
patch -Np0 -i ../patches/gcc-9.1.0-void-patches/ada-shared.patch
patch -Np0 -i ../patches/gcc-9.1.0-void-patches/fix-cxxflags-passing.patch
patch -Np0 -i ../patches/gcc-9.1.0-void-patches/fix-musl-execinfo.patch
patch -Np0 -i ../patches/gcc-9.1.0-void-patches/libgcc-musl-ldbl128-config.patch
patch -Np0 -i ../patches/gcc-9.1.0-void-patches/musl-ada.patch
patch -Np0 -i ../patches/gcc-9.1.0-void-patches/no-stack_chk_fail_local.patch
patch -Np0 -i ../patches/gcc-9.1.0-void-patches/non-nullness.patch
case $(uname -m) in
  x86_64)
    sed -e '/m64=/s/lib64/lib/' \
        -i.orig gcc/config/i386/t-linux64
 ;;
esac
echo "[ CT 5/6 - $PACKAGE Final ] Configure source..." |& tee -a  ~/build.log  &&
mkdir -v build && cd  build &&
AR=ar LDFLAGS="-Wl,-rpath,/cross-tools/lib" \
../configure \
    --prefix=/cross-tools \
    --build=${MLFS_HOST} \
    --host=${MLFS_HOST} \
    --target=${MLFS_TARGET} \
    --disable-multilib \
    --with-sysroot=/cross-tools \
    --disable-nls \
    --enable-shared \
    --enable-languages=c,c++ \
    --enable-threads=posix \
    --enable-clocale=generic \
    --enable-libstdcxx-time \
    --enable-fully-dynamic-string \
    --disable-symvers \
    --disable-libsanitizer \
    --disable-lto-plugin \
    --disable-libssp &&

echo "[ CT 5/6 - $PACKAGE Final ] Compile.." |& tee -a  ~/build.log &&
make AS_FOR_TARGET="${MLFS_TARGET}-as" \
     LD_FOR_TARGET="${MLFS_TARGET}-ld" $MJ  &&

echo "[ CT 5/6 - $PACKAGE Final ] Install ..." |& tee -a  ~/build.log &&
make install &&
cd ../..  && rm -rf $PACKAGE

