#! /bin/bash
# syntax *.build <package.tar.xz> <number of make jobs>

source $MLFS/sources/scripts/000-autobuild.config &&

export PACKAGE=$(echo "$1" | sed -n '/\.tar\.xz$/s///p' )
cd $PACKAGE &&
############################################################

export CC="${MLFS_TARGET}-gcc" &&
export CXX="${MLFS_TARGET}-g++" &&
export AR="${MLFS_TARGET}-ar" &&
export AS="${MLFS_TARGET}-as" &&
export RANLIB="${MLFS_TARGET}-ranlib" &&
export LD="${MLFS_TARGET}-ld" &&
export STRIP="${MLFS_TARGET}-strip" &&

case $(uname -m) in
  x86_64)  ln -sv lib /tools/lib64 ;;
esac &&

echo "[ TC 2/31 - $PACKAGE ] Configuring ..." |& tee -a  ~/build.log &&
mkdir -v build && cd build
../configure                   \
    --target=${MLFS_TARGET}    \
    --build=${MLFS_HOST}       \
    --host=${MLFS_TARGET}      \
    --prefix=/tools            \
    --disable-nls              \
    --disable-werror           \
    --with-lib-path=/tools/lib \
    --with-sysroot &&

echo "[ TC 2/31 - $PACKAGE ] Compiling ..." |& tee -a  ~/build.log &&
make $MJ &&

echo "[ TC 2/31 - $PACKAGE ] Installing ..." |& tee -a  ~/build.log &&
make install &&
make -C ld clean $MJ &&
make -C ld LIB_PATH=/usr/lib:/lib $MJ &&
cp -v ld/ld-new /tools/bin
############################################################
cd ../.. && rm -rf $PACKAGE


