#! /bin/bash
echo "[ TC - MODIFY ] Adjusting Toolchain..." &&
export SPECFILE=`dirname $(${MLFS_TARGET}-gcc -print-libgcc-file-name)`/specs &&
${MLFS_TARGET}-gcc -dumpspecs > specs &&

# Modify dumped specs file for every instance of:
# /lib/ld-musl-$ARCH.so.1 to /tools/lib/ld-musl-$ARCH.so.1
echo "[ TC - INSPECT ] Modified GCC Specs:" |& tee -a  ~/build.log &&
case $(uname -m) in
  x86_64) sed -i 's/\/lib\/ld-musl-x86_64.so.1/\/tools\/lib\/ld-musl-x86_64.so.1/g' specs
          # check with
          grep "/tools/lib/ld-musl-x86_64.so.1" specs  --color=auto |& tee -a  ~/build.log
          ;;
  i686)   sed -i 's/\/lib\/ld-musl-i386.so.1/\/tools\/lib\/ld-musl-i386.so.1/g' specs
          # check with
          grep "/tools/lib/ld-musl-i386.so.1" specs  --color=auto |& tee -a  ~/build.log
          ;;
  arm*)   sed -i 's/\/lib\/ld-musl-arm/\/tools\/lib\/ld-musl-arm/g' specs
          # check with
          grep "/tools/lib/ld-musl-arm" specs  --color=auto |& tee -a  ~/build.log
          ;;
esac &&
mv -v specs $SPECFILE
unset SPECFILE

echo "[ TC - TEST ] Testing Tolchain: " |& tee -a  ~/build.log &&
echo 'int main(){}' > dummy.c &&
${MLFS_TARGET}-gcc dummy.c &&
${MLFS_TARGET}-readelf -l a.out | grep Requesting |& tee -a  ~/build.log &&
rm -v a.out dummy.c
