#! /bin/bash
# syntax *.build <package.tar.xz> <number of make jobs>

source $MLFS/sources/scripts/000-autobuild.config &&

export PACKAGE=$(echo "$1" | sed -n '/\.tar\.xz$/s///p' ) &&
export PVER=$(echo "$1" | sed -n '/\.tar\.xz$/s///p' | cut -d "-" -f 2 ) &&
cd $PACKAGE &&
############################################################
export CC="${MLFS_TARGET}-gcc" &&
export CXX="${MLFS_TARGET}-g++" &&
export AR="${MLFS_TARGET}-ar" &&
export AS="${MLFS_TARGET}-as" &&
export RANLIB="${MLFS_TARGET}-ranlib" &&
export LD="${MLFS_TARGET}-ld" &&
export STRIP="${MLFS_TARGET}-strip" &&

echo "[ TC 4/31 - $PACKAGE LIBSTDCXX ] Patching  source ..." |& tee -a  ~/build.log &&
patch -Np0 -i ../patches/gcc-9.1.0-void-patches/0010-ldbl128-config.patch
patch -Np0 -i ../patches/gcc-9.1.0-void-patches/ada-shared.patch
patch -Np0 -i ../patches/gcc-9.1.0-void-patches/fix-cxxflags-passing.patch
patch -Np0 -i ../patches/gcc-9.1.0-void-patches/fix-musl-execinfo.patch
patch -Np0 -i ../patches/gcc-9.1.0-void-patches/libgcc-musl-ldbl128-config.patch
patch -Np0 -i ../patches/gcc-9.1.0-void-patches/musl-ada.patch
patch -Np0 -i ../patches/gcc-9.1.0-void-patches/no-stack_chk_fail_local.patch
patch -Np0 -i ../patches/gcc-9.1.0-void-patches/non-nullness.patch

echo "[ TC 4/31 - $PACKAGE LIBSTDCXX ] Configure source ..." |& tee -a  ~/build.log &&
mkdir -v build && cd build
../libstdc++-v3/configure           \
    --target=${MLFS_TARGET}         \
    --build=${MLFS_HOST}            \
    --host=${MLFS_TARGET}           \
    --prefix=/tools                 \
    --disable-multilib              \
    --disable-nls                   \
    --disable-libstdcxx-threads     \
    --disable-libstdcxx-pch         \
    --with-gxx-include-dir=/tools/${MLFS_TARGET}/include/c++/$PVER &&
    
echo "[ TC 4/31 - $PACKAGE LIBSTDCXX ] Compiling ..." |& tee -a  ~/build.log &&
make $MJ &&

echo "[ TC 4/31 - $PACKAGE LIBSTDCXX ] Installing ..." |& tee -a  ~/build.log &&
make install &&

############################################################
cd ../.. && rm -rf $PACKAGE
